review structure app + cleanup
mappex/react-burger pull request #1
Opened 2023-02-22 20:52 UTC by mappex

2023-02-23 04:19 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами и правильно используете  PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята. Вы можете сразу приступить к финальному этапу сдачи работы и исправить эти моменты во время него.

Необходимо исправить:
- Файл App.tests.tsx необходимо удалить, он не будет использоваться в проекте.
- В проекте есть два файла стилей для index.tsx - необходимо оставить один.
- Header это отдельный компонент и он должен быть в своей директории, а не внутри директории `app`.
- Оберните главные блоки сайта в тег в `main` в компоненте `App` - это улучшает семантику, что помогает в SEO продвижении сайтов.
- При запуске проекта не отображаются картинки. 
<img width="1001" alt="Снимок экрана 2023-02-23 в 07 06 45" src="https://user-images.githubusercontent.com/60173362/220819208-5d942835-74af-4dce-bcba-56ceed65850f.png">
- При запуске проекта eslint выдает ошибку 
<img width="1440" alt="Снимок экрана 2023-02-23 в 07 07 34" src="https://user-images.githubusercontent.com/60173362/220819285-2a381d2e-09e9-4cbb-b797-b23d310d072b.png">

- во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать
- Допишите типизацию ингредиента и используйте всюду где он передается.

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Используется `isRequired`
- Макет соответствует дизайну
- Используется pretier и eslint

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-23 04:19 UTC, andryxxa93 commented on src/components/burger/constructor/index.jsx
> +function BurgerConstructor(props) {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-02-23 04:19 UTC, andryxxa93 commented on src/components/burger/constructor/index.jsx
> +    image: PropTypes.string.isRequired,
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-02-23 04:19 UTC, andryxxa93 commented on src/components/burger/ingredients/index.jsx
> +  items: PropTypes.arrayOf(PropTypes.shape({
**Необходимо исправить**
Пропс -`items` это не просто массив объектов с одним полем `type`. Это массив ингредиентов, так он и должен быть типизирован с указанием всех полей передаваемого объекта. Исправьте это во всем проекте.

2023-02-23 04:19 UTC, andryxxa93 commented on tsconfig.json
>  {
**Можно лучше**
В проекте сейчас typescript не используется, поэтому конфиг не нужен. Так же стоит поменять расширение у файлов - App.tsx и index.tsx на `jsx `.

2023-02-23 04:19 UTC, andryxxa93 commented on src/components/app/header/index.jsx
> +            <MenuItem icon={<BurgerIcon type="primary" />} text="Конструктор" link="#" active />
**Можно лучше**
в шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать через стейт

2023-03-03 16:03 UTC, mappex commented on src/components/burger/ingredients/index.jsx
> +  items: PropTypes.arrayOf(PropTypes.shape({
fix

2023-03-03 16:03 UTC, mappex commented on src/components/burger/constructor/index.jsx
> +function BurgerConstructor(props) {
fix

2023-03-03 16:11 UTC, mappex commented on tsconfig.json
>  {
Расширение поменял, но удалять typescript не вижу смысла. Так как скоро придется его возвращать. Да и на курсе нам предлагают создать проект сразу с указанием TS

2023-03-03 16:49 UTC, mappex commented on src/components/burger/constructor/index.jsx
> +    image: PropTypes.string.isRequired,
fix

2023-03-03 16:49 UTC, mappex commented on tsconfig.json
>  {
fix

2023-03-03 16:52 UTC, mappex commented on src/components/app/header/index.jsx
> +            <MenuItem icon={<BurgerIcon type="primary" />} text="Конструктор" link="#" active />
не понятно. прошу объяснить, что не так

2023-03-04 06:10 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Вы можете приступить к финальному этапу сдачи работы. Для этого закройте мержом текущий `pull-request`, а когда выполните финальный этап откройте новый `pull-request` и переведите работу на проверку.

Что необходимо будет исправить чтобы работа была принята:
- У вас в проекте есть два компоненты `App`. Один находится в src/app.jsx - его необходимо удалить, он не нужен.
- поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента - его не нужно использовать.

Удачной работы!

2023-03-04 06:10 UTC, andryxxa93 commented on src/components/ingredients/category/index.jsx
> +            value = { item.__v }
**Необходимо исправить**
поле ингредиента `__v` не имеет никакого отношения к счетчику ингредиента, поле `__v` это это версия документа в базе данных `mongo` и не должно никак использоваться в проекте

2023-03-04 07:07 UTC, merged